### ISSUE TITLE
Href tidak ada linknya

### ISSUE THREAD

**Issue by donny1412** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#1]
Pada halaman service.html tombol admin ketika ditekan tidak memunculkan apa-apa dan hanya melakukan reload.
<img width="960" alt="tamoriginal1" src="https://user-images.githubusercontent.com/55181699/66980671-cda29880-f0db-11e9-894a-5ba70b170f95.png">

**Comment by Alpha666** [comment]
Dah fix semua gan :v
