### ISSUE TITLE
ketika tulisan smartfx diklik di page aboutus.php, page beralih ke index.html

### ISSUE THREAD

**Issue by agung56** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#11]
ketika tulisan smartfx diklik di page aboutus.php, page beralih ke index.html
![html](https://user-images.githubusercontent.com/50097116/68192859-96415080-ffe4-11e9-9b0c-5a870f2b21ec.png)

**Comment by anggadaputra11319** [comment]
sudah di link ke index.php :+1:
