### ISSUE TITLE
Saran Tampilan Login 

### ISSUE THREAD

**Issue by Rezaaisyi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#12]
![image](https://user-images.githubusercontent.com/55181853/68219899-55176380-0019-11ea-88ca-96e479b7d85d.png)
Selamat Malam kawan !! secara fungsional sudah sangat baik, tapi saya punya sedikit saran untuk halaman login bisa dihias agar lebih menarik. Terima kasih

**Comment by anggadaputra11319** [comment]
sudah diubah :+1:
