### ISSUE TITLE
Reset Password tidak berfungsi

### ISSUE THREAD

**Issue by MilenFifi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#2]
saat mencoba reset password ngga bisa gan, mungkin bisa perbaiki lagi gan.
tadi sih ada undetified apa gitu waktu dihomepage setelah login dibagian bawah reset password. seingetku line 14 kali yg error
![Screenshot (8)](https://user-images.githubusercontent.com/55182134/66994043-d785c500-f0f6-11e9-9980-951642e50052.png)

**Comment by MilenFifi** [comment]
tp gatau lagi kalau salah line ya

**Comment by Alpha666** [comment]
Hmmmm mungkin bisa di coba lagi fi soalnya robby,aku sama angga coba bisa kok

**Comment by MilenFifi** [comment]
oke udah bisa, tapi mungkin bisa langsung masuk aja gausah login lagi.

**Comment by Alpha666** [comment]
Oke
