### ISSUE TITLE
Undefined Index pada Homepage

### ISSUE THREAD

**Issue by ilyaasha24** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#3]
![image](https://user-images.githubusercontent.com/55181949/67147132-38122f00-f2bc-11e9-851b-20157b53e7d6.png)

**Comment by Alpha666** [comment]
Gimana il kok di aku gapapa eh 

![Screen Shot 2019-10-20 at 10 06 07](https://user-images.githubusercontent.com/53895082/67154160-46defd00-f321-11e9-97a1-06e4645d0fe2.png)
