### ISSUE TITLE
Judul Dobel

### ISSUE THREAD

**Issue by ilyaasha24** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#4]
![image](https://user-images.githubusercontent.com/55181949/67147313-0ac68080-f2be-11e9-8ed4-9a698a545982.png)
![image](https://user-images.githubusercontent.com/55181949/67147320-2598f500-f2be-11e9-9d41-01e96ad6edd3.png)
![image](https://user-images.githubusercontent.com/55181949/67147326-2c276c80-f2be-11e9-87d1-af84dc148596.png)
![image](https://user-images.githubusercontent.com/55181949/67147331-3184b700-f2be-11e9-9f4c-2e315afcdb27.png)

**Comment by Alpha666** [comment]
Fixed ! Thanksss
