### ISSUE TITLE
Reset Password bisa diisi password lama

### ISSUE THREAD

**Issue by ilyaasha24** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#5]
> The rationale is that they want you to change your password. If you try to use the same password, you aren't changing your password. You're re-entering your password.

So, perhaps the question then is why do they want you change your password? They want you to change your password to limit the amount of time a compromised password is valid. Whether this is a helpful mitigation or a case of the cure being worse than the disease is subject to much heated debate, but this is the reason none the less and a fairly standard policy today as it has been for many years.

The thinking is that if you lose your credentials to an attacker, the attacker can then authenticate into the system as you. However, if you're required to change your password regularly, the attacker can only authenticate as you until your next password change, at which time he will no longer have your current credentials, and will once again be locked out of the system. If the system were to let you continue to use the same password, the policy would obviously be useless as the same credentials would continue to work indefinitely.
[https://security.stackexchange.com/questions/137681/why-must-new-password-must-be-different-from-old]

**Comment by Alpha666** [comment]
Untuk hash nya sendiri akan berubah setiap kali kita mengupdate password. Walaupun password nya sama hasil hash nya akan berbeda 

![sebelum](https://user-images.githubusercontent.com/53895082/67154855-fff70480-f32c-11e9-8f0d-6239f50735e9.png)

Ini sebelum di rubah (yang di rubah andrew)

![sesudah](https://user-images.githubusercontent.com/53895082/67154859-0b4a3000-f32d-11e9-951e-80f234f8f83a.png)

Ini sesudah di rubah password nya (dengan password lama)
