### ISSUE TITLE
Pada fitur Testimonials dan Terms of Service disuruh login lagi

### ISSUE THREAD

**Issue by hanaghaliyah** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#7]
Pada fitur Testimonials dan Terms of Service user disuruh login lagi padahal sebelumnya user sudah melakukan login
![Screenshot (18)](https://user-images.githubusercontent.com/26424136/68187237-bff47a80-ffd8-11e9-9874-4d1bc127bf70.png)

**Comment by anggadaputra11319** [comment]
sipp sudah diubah
