### ISSUE TITLE
firstname ditulis dua kali

### ISSUE THREAD

**Issue by agung56** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#8]
pada page contact.php kolom firstname ada dua dan tidak ada last name
![firstname](https://user-images.githubusercontent.com/50097116/68191638-8cb6e900-ffe2-11e9-8600-092774c2fb36.png)

**Comment by anggadaputra11319** [comment]
sipp sudah jadi Last Name satunya
