### ISSUE TITLE
pada testi.php tulisan login belum diubah terms.php juga sama

### ISSUE THREAD

**Issue by agung56** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-tamoriginal#9]
tulisan login pada testi.php belum diubah dan session hilang
![testi](https://user-images.githubusercontent.com/50097116/68192158-837a4c00-ffe3-11e9-8a0a-6ac1f15442ce.png)

**Comment by anggadaputra11319** [comment]
sipp sudah diubah
